### ISSUE TITLE
GameDirectory will be supported?

### ISSUE THREAD

**Issue by nanikit** [Zingabopp/BeatSaberModdingTools#14]
I'm using [BeatSaberModdingTools.Tasks v2.0.0-beta2](https://github.com/Zingabopp/BeatSaberModdingTools.Tasks/releases/tag/2.0.0-beta2) with it and whenever I build my project it prints the following warning.

```
.nuget\packages\beatsabermoddingtools.tasks\2.0.0-beta1\build\BuildTypes\BSMT.BSIPA.targets(5,9): warning : 'BeatSaberDir' property has been deprecated, please switch to 'GameDirectory' to set the Beat Saber path for your project.
```

But I can't use `GameDirectory` because BeatSaberModdingTools generates only `BeatSaberDir`. How can I clear this warning?

**Comment by Zingabopp** [comment]
You can update to beta4, it gets rid of the warning iirc. The warning doesn't hurt anything (besides being annoying), `GameDirectory` is planned for the future.
