### ISSUE TITLE
Can't open solutions in MacOS Catalina w/ VS Studio

### ISSUE THREAD

**Issue by bferguson3** [Zingabopp/BeatSaberModdingTools#8]
Hi,

Cloned your repo and installed the newest VS Studio for mac, but none of the solutions open, for a variety of reasons.

Root sln: Says "This project type is not supported" or "unknown project type" for all folders
Other plugins: "Unknown solution file type: <hash string>"

If I just plain need windows 10 for this feel free to close

**Comment by Zingabopp** [comment]
VS for Mac is completely separate than VS for Windows and their extensions aren't cross-platform, so I'm guessing that's why.
